global_exclude_dirs:
    - vendor
    - provider
    - tests

exclude_patterns:
    - .gitignore

rules:
    web.default_favicon:
        enabled: false
    web.missing_favicon:
        enabled: false